name: bootcomp
channels:
  - defaults
dependencies:
  - matplotlib=3.0.2
  - numba=0.42.0
  - numpy=1.16.2
  - numpy-base=1.16.2
  - pandas=0.24.1
  - pytest=4.3.0
  - python=3.7.2
  - scipy=1.2.1
  - seaborn=0.9.0
  - statsmodels=0.9.0


